
import {
  Sparkles,
  Stars,
  Atom,
  Telescope,
  Compass,
  User,
  Calendar,
  Lightbulb,
  CheckCircle
} from 'lucide-react';

export const ANALYSIS_STAGES = [
  {
    id: 'init',
    label: 'Initialisation',
    icon: Sparkles,
    progress: 5,
    color: 'from-purple-500 to-purple-600',
    description: 'Préparation de votre espace astral personnalisé',
    duration: 500,
  },
  {
    id: 'planets',
    label: 'Positions',
    icon: Stars,
    progress: 15,
    color: 'from-blue-500 to-blue-600',
    description: 'Calcul des positions planétaires au moment de votre naissance',
    duration: 3000,
  },
  {
    id: 'aspects',
    label: 'Aspects',
    icon: Atom,
    progress: 30,
    color: 'from-cyan-500 to-cyan-600',
    description: 'Analyse des aspects et configurations planétaires',
    duration: 2000,
  },
  {
    id: 'natal',
    label: 'Thème Natal',
    icon: Telescope,
    progress: 45,
    color: 'from-indigo-500 to-indigo-600',
    description: 'Construction de votre thème natal complet',
    duration: 5000,
  },
  {
    id: 'mission',
    label: 'Mission de Vie',
    icon: Compass,
    progress: 60,
    color: 'from-violet-500 to-violet-600',
    description: 'Révélation de votre mission de vie et chemin spirituel',
    duration: 3000,
  },
  {
    id: 'personality',
    label: 'Personnalité',
    icon: User,
    progress: 75,
    color: 'from-pink-500 to-pink-600',
    description: 'Analyse approfondie de votre personnalité unique',
    duration: 3000,
  },
  {
    id: 'previsions',
    label: 'Prévisions',
    icon: Calendar,
    progress: 90,
    color: 'from-rose-500 to-rose-600',
    description: 'Calcul de vos prévisions astrologiques',
    duration: 2000,
  },
  {
    id: 'recommendations',
    label: 'Recommandations',
    icon: Lightbulb,
    progress: 95,
    color: 'from-amber-500 to-amber-600',
    description: 'Formulation de recommandations personnalisées',
    duration: 1000,
  },
  {
    id: 'completed',
    label: 'Terminé',
    icon: CheckCircle,
    progress: 100,
    color: 'from-green-500 to-green-600',
    description: 'Votre analyse complète est prête !',
    duration: 1000,
  },
];