import { Star, Hash, Flame, Sparkles, ShoppingCart, BookOpen } from "lucide-react";
import { CategoryType } from "@/components/profil/ProfilCategories";

export const useProfilCategories = () => [
  {
    id: "astrologie",
    title: "ASTROLOGIE",
    subtitle: "Découvre Ton Chemin de Vie",
    icon: Star,
    color: "from-purple-600 to-pink-600",
    gradient: "from-purple-500/10 to-pink-500/10",
    badge: "Populaire",
    badgeColor: "bg-purple-500",
    description: "Explore les influences cosmiques qui façonnent ta destinée",
    link: "/secured/astrologie",
    stats: "4 domaines",
  },
  {
    id: "numerologie",
    title: "NUMÉROLOGIE",
    subtitle: "Les Nombres Révèlent Ton Destin",
    icon: Hash,
    color: "from-indigo-600 to-purple-600",
    gradient: "from-indigo-500/10 to-purple-500/10",
    badge: "Mystique",
    badgeColor: "bg-indigo-500",
    description: "Décode les mystères cachés dans tes nombres personnels",
    link: "/secured/numerologie",
    stats: "5 analyses",
  },
  {
    id: "spiritualite",
    title: "TESTAMENT DE LA CONNAISSANCE",
    subtitle: "Sagesse Ancestrale",
    icon: Flame,
    color: "from-orange-600 to-red-600",
    gradient: "from-orange-500/10 to-red-500/10",
    badge: "Authentique",
    badgeColor: "bg-orange-500",
    description: "Connecte-toi aux forces invisibles et aux ancêtres",
    link: "/secured/spiritualite",
    stats: "Millénaire",
  },
  {
    id: "invocations",
    title: "RITUELS MAGIQUES",
    subtitle: "Manifeste Tes Intentions",
    icon: Sparkles,
    color: "from-amber-600 to-yellow-600",
    gradient: "from-amber-500/10 to-yellow-500/10",
    badge: "Puissant",
    badgeColor: "bg-amber-500",
    description: "Pratiques ésotériques pour manifester tes intentions",
    link: "/secured/astrologie-africaine",
    stats: "Garantis",
  },
  {
    id: "marche",
    title: "MARCHÉ DES OFFRANDES",
    subtitle: "Objets Sacrés & Rituels",
    icon: ShoppingCart,
    color: "from-green-600 to-emerald-600",
    gradient: "from-green-500/10 to-emerald-500/10",
    badge: "Nouveauté",
    badgeColor: "bg-green-500",
    description: "Découvre les offrandes sacrées authentiques",
    link: "/secured/marcheoffrandes",
    stats: "200+ produits",
  },
  {
    id: "librairie",
    title: "LIBRAIRIE ÉSOTÉRIQUE",
    subtitle: "Sagesse & Connaissance",
    icon: BookOpen,
    color: "from-blue-600 to-cyan-600",
    gradient: "from-blue-500/10 to-cyan-500/10",
    badge: "Best-seller",
    badgeColor: "bg-blue-500",
    description: "Collection de livres sacrés et guides spirituels",
    link: "/secured/livres",
    stats: "50+ livres",
  },
] as CategoryType[];
